# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c5ecc13cf4bace29e6b807041b4032a8"
name = "test-app"
handle = "test-app-12001"
application_url = "https://622e-122-161-50-190.ngrok-free.app/"
embedded = true

[webhooks]
api_version = "2025-04"

[auth]
redirect_urls = [ "https://622e-122-161-50-190.ngrok-free.app/auth/callback" ]

[app_proxy]
url = "https://cbbb-182-71-160-186.ngrok-free.app/app-proxy"
subpath = "app"
prefix = "apps"

[pos]
embedded = false
